---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    io.kompose.service: airflow

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: quebaka
  name: quebaka
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: quebaka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: airflow
    spec:
      containers:
        - env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: TZ
              value: Africa/Johannesburg
          image: zubair/airflow-public:latest
          name: airflow
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: quebaka
  name: quebaka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quebaka
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert -f .\docker-compose.yml --out manifest-queue-1s-public.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: quebaka
    spec:
      containers:
        - env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: MYSQL_ROOT_PASSWORD
              value: bendyourarmstolooklikewings
            - name: TZ
              value: Africa/Johannesburg
          image: zubair/quebaka-public:latest
          name: quebaka
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred